export type SeccionDocumento = {
  titulo: string
  intro?: string
  items: string[]
  subsecciones?: { titulo: string; items: string[] }[]
}

export type Documento = {
  id: string
  titulo: string
  subtitulo: string
  categoria: 'checklist' | 'reglamento' | 'politica' | 'procedimiento' | 'formato'
  descripcion: string
  objetivo: string
  secciones: SeccionDocumento[]
  compromiso?: string
  camposFormato?: { label: string; altura?: 'normal' | 'grande' }[]
}

export const documentos: Documento[] = [
  {
    id: 'soporte-remoto-giras',
    titulo: 'Checklist Operativo',
    subtitulo: 'Equipo de Soporte Remoto en Giras / Eventos Presenciales',
    categoria: 'checklist',
    descripcion: 'Responsabilidades y procedimientos del equipo remoto durante giras y eventos presenciales.',
    objetivo: 'Garantizar que toda la información recibida desde el evento presencial sea capturada, validada, procesada y atendida correctamente, asegurando que los clientes reciban sus accesos, mensajes de bienvenida, comunidades, bonos y seguimiento correspondiente en tiempo y forma.',
    secciones: [
      {
        titulo: '1. Responsabilidades Generales del Equipo Remoto',
        intro: 'Durante una gira, el equipo remoto debe entender que la operación no funciona como un día normal. Aunque el evento sea en fin de semana, cada persona debe mantenerse atenta a los grupos, indicaciones del líder y necesidades operativas del evento. Cada integrante del equipo remoto deberá (si aplica):',
        items: [
          'Estar pendiente del grupo operativo de gira.',
          'Estar atento a los mensajes del líder de soporte.',
          'Revisar cuando se notifique que las hojas ya están listas para captura.',
          'Capturar la información asignada con máxima precisión.',
          'Revisar constantemente los Sheets correspondientes.',
          'Dar seguimiento a clientes completos, apartados e interesados.',
          'Enviar mensajes de bienvenida.',
          'Dar accesos a Kajabi.',
          'Dar accesos a Skool.',
          'Dar acceso a comunidades de WhatsApp.',
          'Revisar entregas de mensajes en GHL.',
          'Validar pagos que hayan entrado por links o QR.',
          'Revisar si hay pagos que no vengan reflejados en hojas.',
          'Mantener comunicación con vendedores y equipo presencial.',
          'Atender plataformas normales de soporte durante la gira.',
          'No desconectarse sin confirmar que sus pendientes críticos quedaron cerrados.',
        ],
      },
      {
        titulo: '2. Disponibilidad Durante Giras',
        intro: 'Durante época de gira, el equipo remoto debe contemplar que puede haber trabajo operativo fuera del horario normal, especialmente después de los eventos. Horarios críticos a considerar:',
        items: [
          'Después de las 2:30 p.m., es muy probable que se solicite apoyo para capturar información del evento de la mañana.',
          'Al día siguiente, máximo a las 9:00 a.m., el equipo debe estar capturando o revisando la información del evento de la tarde/noche.',
          'En fines de semana con gira, el equipo debe mantenerse disponible para capturas, accesos, validaciones y seguimiento.',
          'Ningún integrante debe asumir que por ser fin de semana no habrá actividad operativa.',
          'Si el líder notifica que las hojas están listas, se debe atender la solicitud con prioridad.',
        ],
      },
      {
        titulo: '3. Recepción de Información desde el Evento Presencial',
        intro: 'El equipo remoto recibirá la información del compañero que se encuentra físicamente en el evento. Esta información normalmente llegará mediante Drive, Sheets, fotografías, escaneos o notificación directa del líder. Al recibir la notificación, el equipo debe:',
        items: [
          'Confirmar que recibió el aviso.',
          'Entrar al Drive correspondiente.',
          'Revisar que las hojas estén visibles y legibles.',
          'Verificar que los archivos correspondan al evento correcto.',
          'Confirmar ciudad, fecha y horario del evento.',
          'Revisar si las hojas están clasificadas como interesados, apartados o completos.',
          'Notificar de inmediato si falta alguna hoja.',
          'Notificar si alguna imagen está borrosa, cortada o ilegible.',
          'Confirmar con el líder si hay dudas antes de capturar información delicada.',
          'No capturar información dudosa sin marcarla o reportarla.',
        ],
      },
      {
        titulo: '4. Captura de Información en Sheets',
        intro: 'La captura debe hacerse con extrema atención, ya que de esta información dependen accesos, seguimiento comercial, cobranza, onboarding y experiencia del cliente. Información que debe capturarse correctamente:',
        items: [
          'Nombre completo.',
          'Teléfono.',
          'Correo electrónico.',
          'Ciudad del evento.',
          'Fecha del evento.',
          'Producto o programa adquirido.',
          'Tipo de cliente: completo, apartado o interesado.',
          'Monto pagado.',
          'Monto pendiente, si aplica.',
          'Forma de pago.',
          'Vendedor responsable (Abejas ventas).',
          'Tipo de acceso que corresponde.',
          'Comunidad correspondiente.',
          'Observaciones relevantes.',
          'Estatus actualizado.',
        ],
      },
      {
        titulo: '5. Captura de Pagos y Vouchers',
        intro: 'Cuando la gira sea en México y existan pagos con voucher de Mercado Pago, es obligatorio capturar correctamente la información del comprobante. Checklist para pagos:',
        items: [
          'Revisar si la hoja incluye voucher de Mercado Pago.',
          'Capturar el número de operación en notas.',
          'Validar que el monto coincida con la hoja.',
          'Revisar fecha y hora del pago.',
          'Confirmar forma de pago.',
          'Marcar si el pago está completo o es apartado.',
          'Reportar pagos incompletos, ilegibles o dudosos.',
          'Revisar que no haya pagos por links o QR que no estén en hojas.',
          'Comparar pagos recibidos contra hojas físicas.',
          'Notificar al líder cualquier pago no identificado.',
        ],
      },
      {
        titulo: '6. Revisión de Pagos por Links o QR',
        intro: 'Además de las hojas recibidas, el equipo remoto debe revisar si cayeron pagos por links o códigos QR que no estén reflejados en las hojas del evento. El equipo debe:',
        items: [
          'Revisar pagos recibidos por links.',
          'Revisar pagos recibidos por QR.',
          'Comparar pagos contra las hojas capturadas.',
          'Identificar pagos sin hoja.',
          'Identificar hojas sin pago visible.',
          'Reportar inconsistencias al líder.',
          'Preguntar al área correspondiente antes de asumir estatus.',
          'Registrar en notas cualquier pago pendiente de aclaración.',
          'Dar seguimiento hasta que el pago quede identificado correctamente.',
        ],
      },
      {
        titulo: '7. Mensajes de Bienvenida',
        intro: 'Una vez capturados los clientes correspondientes, se deben enviar los mensajes de bienvenida según el producto, comunidad o acceso que aplique. Checklist de bienvenida:',
        items: [
          'Identificar a los clientes completos.',
          'Enviar mensaje de bienvenida correspondiente.',
          'Confirmar que el mensaje haya sido entregado.',
          'Revisar si el cliente respondió.',
          'Resolver dudas básicas o canalizar al área correspondiente.',
          'Registrar en Sheets si el mensaje fue enviado.',
          'Registrar en notas cualquier caso especial.',
        ],
      },
      {
        titulo: '8. Accesos a Kajabi',
        intro: 'El equipo remoto debe validar que todos los clientes completos reciban acceso a Kajabi cuando corresponda. Para Kajabi se debe:',
        items: [
          'Revisar la lista de clientes completos.',
          'Confirmar que cada cliente tenga correo electrónico.',
          'Dar acceso a Kajabi.',
          'Verificar que el acceso haya sido creado correctamente.',
          'Confirmar que el cliente recibió acceso.',
          'Revisar si algún completo no tiene correo.',
          'Si falta correo, mandar WhatsApp solicitándolo.',
          'Registrar en Sheets que el acceso fue otorgado.',
          'Marcar cualquier caso pendiente.',
          'Dar seguimiento hasta cerrar el acceso.',
          'Si el cliente no tiene correo: enviar mensaje por WhatsApp, registrar en notas y dar seguimiento hasta recibirlo.',
        ],
      },
      {
        titulo: '9. Accesos a Skool',
        intro: 'El equipo remoto debe dar acceso a Skool a las personas correspondientes y revisar cambios de membresía cuando aplique. Checklist de Skool:',
        items: [
          'Revisar quiénes deben ingresar a Skool.',
          'Confirmar nombre y correo del cliente.',
          'Revisar cambio de Standard a Premium.',
          'Confirmar que el cambio se haya realizado correctamente.',
          'Registrar el acceso en Sheets.',
          'Dar seguimiento hasta que el cliente quede dentro correctamente.',
        ],
      },
      {
        titulo: '10. Cambio de Standard a Premium',
        intro: 'Cuando existan personas que ingresan a Skool y deban cambiar de Standard a Premium, el equipo remoto debe verificar que el cambio se haya realizado correctamente. Se debe revisar:',
        items: [
          'Nombre del cliente.',
          'Correo registrado.',
          'Estatus actual en Skool.',
          'Cambio de Standard a Premium.',
        ],
      },
      {
        titulo: '11. Revisión de Mensajes en GHL',
        intro: 'El equipo remoto debe revisar que los mensajes enviados desde GHL hayan sido entregados correctamente a todos los destinatarios. Checklist de GHL:',
        items: [
          'Revisar lista de destinatarios.',
          'Confirmar que los mensajes fueron enviados.',
          'Confirmar que los mensajes fueron entregados.',
          'Detectar mensajes fallidos.',
          'Detectar contactos sin entrega.',
          'Contactar directamente a quienes no recibieron el mensaje.',
          'Registrar el seguimiento realizado.',
          'Reportar fallas recurrentes al líder.',
          'Confirmar que todos los clientes importantes fueron contactados.',
        ],
      },
      {
        titulo: '12. Accesos a Bonos VIP',
        intro: 'Los clientes VIP deben recibir los bonos correspondientes. Para esto, el equipo remoto debe usar la hoja de registro y filtrar correctamente a los VIP. Checklist de bonos VIP:',
        items: [
          'Abrir hoja de registro del evento.',
          'Filtrar por clientes VIP.',
          'Confirmar qué bono corresponde.',
          'Dar acceso a la masterclass correspondiente.',
          'Registrar acceso otorgado.',
          'Revisar que no falte ningún VIP.',
          'Reportar VIP sin correo, teléfono o información incompleta.',
          'Dar seguimiento a cualquier acceso pendiente.',
        ],
      },
      {
        titulo: '13. Revisión Constante de Sheets',
        intro: 'Durante giras, los Sheets pueden actualizarse constantemente porque ventas puede cerrar personas que inicialmente estaban como apartados o interesados. El equipo remoto debe:',
        items: [
          'Revisar constantemente los Sheets o archivos de control.',
          'Verificar si vendedores cerraron personas que estaban como apartados.',
          'Verificar si vendedores cerraron personas que estaban como interesados.',
          'Actualizar estatus del cliente.',
          'Dar accesos correspondientes cuando el cliente pase a completo.',
          'Enviar mensaje de bienvenida si aplica.',
          'Actualizar notas.',
          'Confirmar con ventas si hay dudas.',
          'No dejar cambios de estatus sin procesar.',
        ],
      },
      {
        titulo: '14. Acceso Masivo a Comunidad del Evento',
        intro: 'Cuando corresponda, se debe enviar acceso masivo a la comunidad relacionada con la ciudad o evento. Checklist para comunidad del evento:',
        items: [
          'Identificar la comunidad correspondiente al evento.',
          'Revisar la lista de personas que deben recibir acceso.',
          'Validar teléfonos y correos.',
          'Enviar acceso masivo.',
          'Confirmar entrega del mensaje.',
        ],
      },
      {
        titulo: '15. Comunidades de WhatsApp',
        intro: 'El equipo remoto debe dar acceso y aceptar miembros en las comunidades de WhatsApp correspondientes. Checklist de WhatsApp:',
        items: [
          'Enviar enlace de comunidad correspondiente.',
          'Revisar solicitudes de ingreso.',
          'Aceptar miembros.',
        ],
      },
      {
        titulo: '16. Comunicación con Vendedores',
        intro: 'Durante la gira, los vendedores pueden enviar información, dudas, cierres o aclaraciones por grupos de WhatsApp. El equipo remoto debe:',
        items: [
          'Estar pendiente de los grupos de WhatsApp con vendedores.',
          'Responder mensajes importantes.',
          'Confirmar cierres actualizados.',
          'Validar apartados que se conviertan en completos.',
          'Resolver dudas operativas de accesos.',
          'Pedir información faltante cuando sea necesario.',
          'Reportar al líder cualquier caso crítico.',
          'No dejar mensajes de vendedores sin revisar durante la operación.',
        ],
      },
      {
        titulo: '17. Atención de WhatsApp y Plataformas de Clientes',
        intro: 'Durante giras, los clientes pueden contactar por WhatsApp, GHL, comunidades, plataformas o canales de soporte. El equipo remoto debe revisar:',
        items: [
          'WhatsApp de soporte.',
          'Grupos de WhatsApp.',
          'Comunidades.',
          'GHL.',
          'Kajabi.',
          'Skool.',
          'Correos o formularios si aplica.',
          'Plataformas asignadas en su ruta crítica.',
          'Mensajes de clientes con problemas de acceso.',
          'Mensajes de clientes que no recibieron bienvenida.',
          'Mensajes de clientes con dudas de pago.',
        ],
      },
      {
        titulo: '18. Atención a Casos Incompletos o Dudosos',
        intro: 'Si existe información incompleta, contradictoria o ilegible, el equipo remoto no debe inventar datos ni avanzar sin marcar el caso. En estos casos se debe:',
        items: [
          'Marcar el caso como pendiente.',
          'Escribir observación clara en notas.',
          'Consultar al líder.',
          'Consultar al vendedor si aplica.',
          'Solicitar foto o escaneo más claro.',
          'Pedir correo o teléfono faltante al cliente.',
          'No otorgar accesos incorrectos.',
          'No cambiar estatus sin validación.',
          'Dar seguimiento hasta cerrar el pendiente.',
        ],
      },
      {
        titulo: '19. Cierre de Captura del Evento de la Mañana',
        intro: 'Cuando se notifique que las hojas del evento de la mañana están listas, el equipo debe actuar de inmediato, especialmente después de las 2:30 p.m. Checklist obligatorio:',
        items: [
          'Confirmar recepción de la notificación.',
          'Abrir Drive y Sheets correspondientes.',
          'Revisar legibilidad de las hojas.',
          'Capturar completos.',
          'Capturar apartados (persona en evento).',
          'Capturar interesados (persona en evento).',
          'Registrar números de operación de Mercado Pago si aplica.',
          'Enviar mensajes de bienvenida.',
          'Dar accesos correspondientes.',
          'Revisar GHL.',
          'Revisar Kajabi.',
          'Revisar Skool.',
          'Revisar pagos por link o QR.',
          'Reportar inconsistencias.',
          'Confirmar al líder cuando la captura esté cerrada.',
        ],
      },
      {
        titulo: '20. Cierre de Captura del Evento de la Tarde / Noche',
        intro: 'La información del evento de la tarde/noche debe quedar disponible para que el equipo pueda trabajar a primera hora del día siguiente. Como máximo, a las 9:00 a.m. del día siguiente el equipo debe estar capturando o revisando. Checklist obligatorio:',
        items: [
          'Revisar si las hojas ya fueron subidas al Drive.',
          'Confirmar instrucciones del líder.',
          'Capturar la información pendiente.',
          'Procesar completos.',
          'Procesar apartados.',
          'Procesar interesados.',
          'Dar accesos de Kajabi.',
          'Dar accesos de Skool.',
          'Revisar cambios de Standard a Premium.',
          'Enviar mensajes de bienvenida.',
          'Dar accesos a comunidades de WhatsApp.',
          'Aceptar miembros en comunidades.',
          'Revisar GHL.',
          'Contactar manualmente a clientes sin entrega de mensaje.',
          'Revisar bonos VIP.',
          'Revisar pagos por link o QR.',
          'Confirmar cierre con el líder.',
        ],
      },
      {
        titulo: '21. Cierre Diario del Equipo Remoto',
        intro: 'Antes de cerrar el día o terminar su turno operativo de gira, cada integrante debe asegurarse de que sus pendientes estén concluidos o correctamente reportados. Checklist de cierre:',
        items: [
          'Las hojas asignadas fueron revisadas.',
          'La información fue capturada.',
          'Los datos fueron revisados con precisión.',
          'Los completos fueron procesados.',
          'Los apartados fueron capturados.',
          'Los interesados fueron capturados.',
          'Los números de operación de Mercado Pago fueron registrados en notas (si aplica).',
          'Los mensajes de bienvenida fueron enviados.',
          'Los accesos de Kajabi fueron otorgados.',
          'Los accesos de Skool fueron otorgados.',
          'Los cambios de Standard a Premium fueron revisados.',
          'Los mensajes de GHL fueron revisados.',
          'Los mensajes no entregados fueron contactados directamente.',
          'Los bonos VIP fueron entregados.',
          'Los accesos a masterclass fueron otorgados.',
          'Los accesos a comunidades fueron enviados.',
          'Los miembros pendientes fueron aceptados.',
          'Los grupos de vendedores fueron revisados.',
          'Los WhatsApp y plataformas de clientes fueron revisados.',
          'Los pagos por links o QR fueron revisados.',
          'Las inconsistencias fueron reportadas.',
          'El líder fue notificado del avance o cierre.',
          'La ruta crítica personal fue atendida.',
        ],
      },
      {
        titulo: '22. Errores que No Deben Ocurrir',
        intro: 'El equipo remoto debe evitar estrictamente lo siguiente:',
        items: [
          'Capturar nombres, teléfonos o correos incorrectos.',
          'No revisar si las hojas ya están disponibles.',
          'No estar pendiente del grupo durante gira.',
          'Asumir que por ser fin de semana no habrá trabajo.',
          'No registrar número de operación de Mercado Pago (si aplica).',
          'Dar accesos a clientes equivocados.',
          'No dar acceso a Kajabi a clientes completos.',
          'No pedir correo cuando haga falta.',
          'No revisar cambios de Standard a Premium.',
          'No revisar si los mensajes de GHL fueron entregados.',
          'No contactar manualmente a clientes sin entrega.',
          'No entregar bonos VIP.',
          'No dar acceso a masterclass a clientes VIP.',
          'No aceptar miembros en comunidades.',
          'No revisar mensajes de vendedores.',
          'No revisar pagos por links o QR.',
          'Dejar inconsistencias sin reportar.',
          'Cerrar el día sin avisar estatus al líder.',
          'Ignorar plataformas de soporte durante gira.',
        ],
      },
      {
        titulo: '23. Prioridades del Equipo Remoto Durante Gira',
        intro: 'En caso de tener varias tareas al mismo tiempo, el orden de prioridad será:',
        items: [
          'Atender instrucciones del líder de soporte.',
          'Revisar hojas disponibles para captura.',
          'Capturar completos, apartados e interesados con precisión.',
          'Validar pagos, vouchers, links y QR.',
          'Dar accesos a clientes completos.',
          'Enviar mensajes de bienvenida.',
          'Revisar Kajabi, Skool y cambios de membresía.',
          'Procesar bonos VIP y masterclass.',
          'Revisar GHL y mensajes no entregados.',
          'Dar acceso a comunidades de WhatsApp.',
          'Atender mensajes de vendedores.',
          'Atender plataformas y WhatsApp de clientes.',
          'Actualizar Sheets y notas.',
          'Reportar inconsistencias y cerrar pendientes.',
        ],
      },
      {
        titulo: '24. Estándar de Calidad de Captura',
        intro: 'La captura debe hacerse como si de ella dependiera toda la experiencia del cliente, porque así es. Cada persona debe confirmar:',
        items: [
          'Que el nombre esté bien escrito.',
          'Que el teléfono tenga lada correcta.',
          'Que el correo esté bien escrito.',
          'Que el producto sea correcto.',
          'Que el estatus sea correcto.',
          'Que el monto sea correcto.',
          'Que la ciudad/evento sea correcto.',
          'Que las notas sean claras.',
          'Que el número de operación esté capturado cuando aplique.',
          'Que los accesos se hayan dado al cliente correcto.',
          'Que no haya duplicados.',
          'Que no haya clientes sin seguimiento.',
        ],
      },
    ],
    compromiso: 'Yo, ____________________________________________, declaro que he leído, comprendido y aceptado las responsabilidades correspondientes al rol de Soporte Remoto durante Giras y Eventos Presenciales.\n\nEntiendo que durante una gira mi responsabilidad no se limita a mi horario habitual ni a mis actividades normales de soporte, ya que la operación del evento puede requerir atención especial durante la tarde, noche, fines de semana o a primera hora del día siguiente.\n\nReconozco que, después de las 2:30 p.m., es posible que se me solicite apoyar con la captura del evento de la mañana, y que al día siguiente, máximo a las 9:00 a.m., debo estar disponible para capturar, revisar o procesar la información del evento de la tarde/noche si así lo requiere la operación.\n\nAcepto que mi responsabilidad no termina hasta que la información asignada esté capturada, revisada, procesada, los accesos entregados, las inconsistencias reportadas y el líder haya sido notificado del avance o cierre correspondiente.',
  },
  {
    id: 'operativo-giras',
    titulo: 'Checklist Operativo',
    subtitulo: 'Encargado de Soporte en Evento Presencial / Gira',
    categoria: 'checklist',
    descripcion: 'Responsabilidades y procedimientos del encargado de soporte presente físicamente en el evento.',
    objetivo: 'Garantizar que toda la información generada durante la venta presencial del evento quede correctamente recibida, validada, capturada, escaneada y enviada al equipo de soporte remoto en tiempo y forma, sin descuidar las actividades normales de soporte asignadas en la ruta crítica.',
    secciones: [
      {
        titulo: '1. Responsabilidades Generales del Encargado de Soporte',
        intro: 'Durante la gira, la persona responsable deberá:',
        items: [
          'Cumplir con sus actividades asignadas del evento presencial.',
          'Cumplir con sus actividades normales de soporte.',
          'Atender sus plataformas correspondientes.',
          'Revisar y avanzar su ruta crítica diaria.',
          'Aprovechar los momentos de menor operación del evento para adelantar pendientes.',
          'Mantener comunicación constante con ventas y soporte remoto.',
          'Dar seguimiento activo a la entrega de hojas/contratos por parte del área de ventas.',
          'Asegurar que ninguna hoja se pierda, quede sin escanear o sin capturar.',
        ],
      },
      {
        titulo: '2. Tipos de Hojas que se Reciben al Final del Evento',
        intro: 'Al finalizar la venta del evento, el área de ventas genera hojas que funcionan como contratos o registros comerciales. Estas hojas pueden ser de:',
        items: [
          'Interesados',
          'Apartados',
          'Completos',
          'Cada hoja debe ser revisada, validada, escaneada y capturada según corresponda.',
        ],
      },
      {
        titulo: '3. Validación con el Área de Ventas',
        intro: 'Antes de que soporte pueda capturar cualquier hoja, el área de ventas debe corroborar los pagos y entregar las hojas correspondientes. El encargado de soporte debe:',
        items: [
          'Solicitar al área de ventas las hojas lo antes posible.',
          'Presionar de manera constante y profesional para que ventas entregue las hojas completas.',
          'Confirmar que ventas ya haya corroborado los pagos.',
          'Verificar que las hojas estén clasificadas correctamente como interesados, apartados o completos.',
          'Revisar que las hojas estén legibles.',
          'Revisar que las hojas tengan la información mínima necesaria para su captura.',
          'Reportar de inmediato cualquier hoja incompleta, ilegible o dudosa.',
          'No dejar hojas pendientes sin seguimiento.',
        ],
      },
      {
        titulo: '4. Captura de Información en Sheets',
        intro: 'Una vez que ventas haya validado los pagos y entregado las hojas, se debe capturar la información en el Google Sheets correspondiente. La captura debe incluir:',
        items: [
          'Nombre completo del cliente/prospecto.',
          'Teléfono.',
          'Correo electrónico.',
          'Ciudad/evento.',
          'Tipo de hoja: interesado, apartado o completo.',
          'Producto o programa adquirido/interesado.',
          'Monto pagado o apartado.',
          'Forma de pago, si aplica.',
          'Vendedor responsable (Abejas ventas).',
          'Observaciones relevantes.',
          'Estatus actualizado.',
        ],
      },
      {
        titulo: '5. Escaneo de Hojas',
        intro: 'Todas las hojas físicas deben ser escaneadas y subidas al Drive correspondiente para que el equipo de soporte remoto pueda consultarlas. El encargado debe:',
        items: [
          'Escanear todas las hojas recibidas.',
          'Verificar que cada imagen sea clara y legible.',
          'Confirmar que no falte ninguna hoja.',
          'Nombrar o clasificar los archivos de forma ordenada.',
          'Subir las imágenes al Drive correspondiente.',
          'Confirmar que el equipo de soporte remoto tenga acceso a la carpeta.',
          'Avisar al equipo remoto cuando las hojas ya estén disponibles.',
          'Reportar cualquier problema con escaneo, internet o acceso al Drive.',
        ],
      },
      {
        titulo: '6. Entrega al Equipo de Soporte Remoto',
        intro: 'El equipo de soporte que no se encuentra físicamente en el evento necesita recibir las imágenes escaneadas para poder avanzar con sus procesos. Se debe asegurar que:',
        items: [
          'Todas las hojas estén subidas al Drive.',
          'Las imágenes estén organizadas por ciudad, fecha, evento y tipo de hoja.',
          'El equipo remoto sea notificado inmediatamente.',
          'Se confirme que el equipo remoto pudo visualizar correctamente los archivos.',
          'Se dé seguimiento a cualquier duda del equipo remoto.',
          'No se cierre el día sin confirmar que las hojas quedaron disponibles.',
        ],
      },
      {
        titulo: '7. Eventos con Doble Horario: Mañana y Noche',
        intro: 'Cuando exista evento en la mañana y evento en la noche, se debe tener especial cuidado con los tiempos de entrega.',
        items: [],
        subsecciones: [
          {
            titulo: 'Evento de la Mañana',
            items: [
              'Solicitar hojas al área de ventas inmediatamente después del cierre de venta.',
              'Presionar a ventas para recibir las hojas completas lo antes posible.',
              'Confirmar validación de pagos.',
              'Separar hojas por interesados, apartados y completos.',
              'Capturar los apartados.',
              'Capturar los interesados.',
              'Escanear todas las hojas del evento de la mañana.',
              'Subirlas al Drive correspondiente.',
              'Avisar al equipo remoto que las hojas del evento de la mañana ya están disponibles.',
              'Confirmar que no quedó ninguna hoja pendiente antes de iniciar el segundo evento.',
            ],
          },
          {
            titulo: 'Evento de la Noche',
            items: [
              'Solicitar hojas a ventas inmediatamente al terminar la venta.',
              'Presionar a ventas hasta recibir las hojas completas.',
              'Confirmar validación de pagos.',
              'Separar hojas por interesados, apartados y completos.',
              'Escanear todas las hojas del evento de la noche.',
              'Subir los escaneos al Drive correspondiente.',
              'Confirmar que el equipo remoto pueda acceder a los archivos.',
              'Dejar todo listo para que soporte remoto tenga la información a primera hora del día siguiente.',
            ],
          },
        ],
      },
      {
        titulo: '8. Manejo de Tiempos Durante el Evento',
        intro: 'El encargado de soporte no debe esperar al final del día para avanzar sus responsabilidades. Debe aprovechar los momentos de menor operación para adelantar:',
        items: [
          'Atención de plataformas.',
          'Pendientes de soporte.',
          'Ruta crítica diaria.',
          'Organización de hojas.',
          'Escaneo de documentos.',
          'Captura en Sheets.',
          'Comunicación con soporte remoto.',
        ],
      },
      {
        titulo: '9. Comunicación con el Área de Ventas',
        intro: 'El área de ventas debe entregar las hojas lo más rápido posible. El encargado de soporte es responsable de dar seguimiento hasta recibirlas. Frases sugeridas para seguimiento:',
        items: [
          '"Equipo, necesito las hojas validadas para poder capturarlas y escanearlas."',
          '"¿Qué hojas ya tienen pago corroborado para ir avanzando?"',
          '"Necesito que me entreguen primero las hojas completas y apartados para no retrasar soporte."',
          '"Recuerden que soporte remoto necesita las imágenes hoy para poder trabajar mañana temprano."',
          '"¿Hay alguna hoja pendiente de validar o ya puedo cerrar el paquete?"',
        ],
      },
      {
        titulo: '10. Cierre Diario Obligatorio',
        intro: 'Antes de terminar el día, el encargado debe confirmar que todo quedó cerrado. Checklist de cierre:',
        items: [
          'Todas las hojas fueron recibidas.',
          'Todas las hojas fueron revisadas.',
          'Todas las hojas fueron clasificadas.',
          'Los pagos fueron corroborados por ventas.',
          'La información fue capturada en Sheets.',
          'Los apartados fueron capturados (evento mañana).',
          'Los interesados fueron capturados (evento mañana).',
          'Las hojas completas fueron registradas o canalizadas correctamente.',
          'Todas las hojas fueron escaneadas.',
          'Todas las imágenes fueron subidas al Drive.',
          'El equipo remoto fue notificado.',
          'Se confirmó acceso a los archivos.',
          'No quedaron hojas físicas sin control.',
          'No quedaron pendientes críticos sin reportar.',
          'La ruta crítica del día fue atendida.',
          'Las plataformas de soporte fueron revisadas.',
        ],
      },
      {
        titulo: '11. Errores que No Deben Ocurrir',
        intro: 'El encargado de soporte debe evitar estrictamente lo siguiente:',
        items: [
          'Dejar hojas sin escanear.',
          'Dejar hojas sin capturar.',
          'Esperar demasiado tiempo para pedir hojas a ventas.',
          'No presionar a ventas por la entrega de documentos.',
          'Subir imágenes borrosas o incompletas.',
          'No avisar al equipo remoto.',
          'Perder hojas físicas.',
          'Capturar datos incorrectos.',
          'No revisar su ruta crítica.',
          'Descuidar plataformas de soporte durante la gira.',
          'Irse del evento sin cerrar pendientes.',
          'Tomar como día libre un día sin gira sin antes terminar sus actividades críticas.',
        ],
      },
      {
        titulo: '12. Prioridades del Rol',
        intro: 'En caso de tener muchas actividades al mismo tiempo, el orden de prioridad será:',
        items: [
          'Control físico de hojas y contratos.',
          'Validación con ventas sobre pagos y estatus.',
          'Escaneo y subida inmediata al Drive.',
          'Captura de apartados e interesados.',
          'Comunicación con soporte remoto.',
          'Atención de plataformas de soporte.',
          'Avance de ruta crítica diaria.',
          'Cierre y reporte final del día.',
        ],
      },
    ],
    compromiso: 'Yo, ____________________________________________, declaro que he leído, comprendido y aceptado las responsabilidades correspondientes al rol de Encargado de Soporte en Evento Presencial / Gira.\n\nEntiendo que durante los días de evento soy responsable de apoyar la operación presencial, dar seguimiento al área de ventas, recibir las hojas generadas por la venta, corroborar que hayan sido validadas, capturar la información correspondiente, escanear los documentos y enviarlos al equipo de soporte remoto mediante Drive en los tiempos establecidos.\n\nAcepto que mi responsabilidad no termina hasta que las hojas estén correctamente recibidas, capturadas, escaneadas, subidas al Drive y notificadas al equipo correspondiente.',
  },
  {
    id: 'manual-reglas',
    titulo: 'Manual de Reglas',
    subtitulo: 'Equipo de Atención al Cliente',
    categoria: 'reglamento',
    descripcion: 'Reglas de comunicación, coordinación, respeto y calidad en el servicio que todo miembro del equipo debe conocer y aplicar.',
    objetivo: 'Establecer las reglas base que todo miembro del equipo de atención al cliente debe conocer, aplicar y respetar en su trabajo diario.',
    secciones: [
      {
        titulo: 'Reglas de Comunicación',
        items: [
          'Avisar antes de actuar en cualquier decisión que pueda afectar al cliente, al equipo o a la imagen de la empresa.',
          'Usar siempre el canal oficial de comunicación para informar cambios, dudas o avances.',
          'Responder dentro de un tiempo establecido (máximo 15 min en horario laboral) a mensajes internos.',
          'Escalar situaciones críticas al líder antes de dar una respuesta definitiva al cliente.',
        ],
      },
      {
        titulo: 'Reglas de Coordinación',
        items: [
          'Registrar las decisiones importantes en un documento compartido o tablero.',
          'Seguir la cadena de comunicación: decisiones operativas se toman en equipo, decisiones estratégicas se consultan con dirección.',
          'Respetar los acuerdos de las juntas: una vez definidos los lineamientos, se aplican de manera uniforme.',
        ],
      },
      {
        titulo: 'Reglas de Respeto y Cultura',
        items: [
          'Puntualidad en juntas y horarios de trabajo como señal de respeto al equipo.',
          'Retroalimentación siempre en tono constructivo, nunca personal.',
          'Actuar con iniciativa, pero nunca en aislamiento: toda acción debe estar alineada a la visión del equipo.',
        ],
      },
      {
        titulo: 'Reglas de Calidad en el Servicio',
        items: [
          'No cerrar un caso sin documentarlo (qué pasó, cómo se resolvió).',
          'Seguir guías y protocolos de atención al cliente de manera uniforme, salvo autorización expresa de cambios.',
          'Cuidar el tono de comunicación con clientes y compañeros, manteniendo amabilidad y profesionalismo.',
        ],
      },
    ],
    compromiso: 'Reconozco haber leído estas reglas y me comprometo a aplicarlas en mi trabajo diario.',
  },
  {
    id: 'catalogo-incidencias',
    titulo: 'Catálogo de Incidencias',
    subtitulo: 'Equipo de Atención al Cliente',
    categoria: 'politica',
    descripcion: 'Clasificación de incidencias en niveles Leve, Media y Grave para definir qué situaciones requieren registro y seguimiento formal.',
    objetivo: 'Dar claridad al equipo sobre qué situaciones requieren registro y seguimiento, clasificadas en tres niveles de gravedad. Cada incidencia registrada será acompañada del Formato de Incidencias y el compromiso de mejora por parte del colaborador.',
    secciones: [
      {
        titulo: 'Incidencias Leves',
        items: [
          'Retraso ocasional en contestar mensajes internos (más de 2 horas en horario laboral).',
          'Olvidar registrar una acción o decisión en el canal/documento oficial.',
          'Llegar tarde a una junta de forma aislada.',
          'Error menor en el uso de protocolos de comunicación al cliente (sin impacto negativo).',
        ],
      },
      {
        titulo: 'Incidencias Medias',
        items: [
          'Reincidencia en retrasos o falta de comunicación.',
          'Tomar decisiones que afectan a otro miembro sin informarlo.',
          'No respetar un acuerdo de junta previamente establecido.',
          'Cerrar un caso de cliente sin documentar la solución.',
          'Ausencia injustificada en una junta importante.',
          'Irse de su lugar de trabajo sin avisar dentro de horario laboral.',
          'Irse a platicar a otras áreas temas fuera de trabajo dentro de horario laboral.',
          'Ayudar a otras áreas sin comunicar o pedir permiso al líder.',
        ],
      },
      {
        titulo: 'Incidencias Graves',
        items: [
          'Reincidencia en la misma falta después de advertencia.',
          'Aplicar un cambio de política o procedimiento sin autorización.',
          'Dar una respuesta al cliente contraria a los protocolos, causando insatisfacción.',
          'Comunicar información sensible al cliente sin validación.',
          'Filtrar información delicada del equipo a otras áreas sin autorización.',
          'Faltas reiteradas de puntualidad que afectan al equipo.',
          'Actitudes irrespetuosas o lenguaje inadecuado hacia compañeros o clientes.',
        ],
      },
    ],
  },
  {
    id: 'formato-incidencias',
    titulo: 'Formato de Incidencias',
    subtitulo: 'Faltas a los Acuerdos',
    categoria: 'formato',
    descripcion: 'Formato oficial para registrar incidencias o faltas a los acuerdos del equipo. Busca dar claridad, responsabilidad y compromiso de mejora.',
    objetivo: 'Registrar incidencias o faltas a los acuerdos establecidos en el Manual de Reglas del Equipo de Atención al Cliente. Su llenado busca dar claridad, responsabilidad y compromiso de mejora.',
    secciones: [],
    camposFormato: [
      { label: 'Fecha' },
      { label: 'Nombre del Colaborador' },
      { label: 'Área / Puesto' },
      { label: 'Tipo de incidencia' },
      { label: 'Descripción de la incidencia', altura: 'grande' },
      { label: 'Acuerdo establecido previamente relacionado', altura: 'grande' },
      { label: 'Acción correctiva o compromiso del colaborador', altura: 'grande' },
      { label: 'Fecha límite de cumplimiento' },
      { label: 'Observaciones del líder', altura: 'grande' },
    ],
  },
]

export const CATEGORIA_LABELS: Record<Documento['categoria'], string> = {
  checklist:     'Checklist',
  reglamento:    'Reglamento',
  politica:      'Política',
  procedimiento: 'Procedimiento',
  formato:       'Formato',
}

export const CATEGORIA_COLORS: Record<Documento['categoria'], { bg: string; text: string; border: string }> = {
  checklist:    { bg: 'rgba(70,140,220,0.1)',  text: '#6aaddc', border: 'rgba(70,140,220,0.25)' },
  reglamento:   { bg: 'rgba(180,130,220,0.1)', text: '#c08ce0', border: 'rgba(180,130,220,0.25)' },
  politica:     { bg: 'rgba(220,160,70,0.1)',  text: '#dcb83c', border: 'rgba(220,160,70,0.25)' },
  procedimiento:{ bg: 'rgba(70,200,140,0.1)',  text: '#60c898', border: 'rgba(70,200,140,0.25)' },
  formato:      { bg: 'rgba(220,100,100,0.1)', text: '#dc8080', border: 'rgba(220,100,100,0.25)' },
}
