// Enlaces de pago estáticos (Black Access, Webinars, Presenciales) — viven
// aquí en vez de directo en app/pagos/page.tsx para que también puedan
// indexarse en el buscador global (app/buscar/page.tsx) sin duplicar datos.

export type LinkItem = { nombre: string; precio: string; url?: string }
export type Subseccion = { titulo: string; items: LinkItem[] }

/* ─── Black Access / Bootcamp ───────────────────────────────────────────── */
// Cada producto usa el nombre EXACTO de su categoría (tal como en la hoja),
// con el monto aparte — sin repetir "GENERAL ACCESS"/"BLACK ACCESS" en el nombre.
export const BLACK_ACCESS: Subseccion[] = [
  {
    titulo: 'Bootcamp y Links Oficiales',
    items: [
      { nombre: 'BOOTCAMP MEX PAUTA · 05,06 Y 07 DE JUNIO', precio: '$13,036', url: 'https://bootcampsinergetico.com/?utm_source=clubsinergetico' },
      { nombre: 'BOLETERA BOOTCAMP (WhatsApp)',             precio: '$13,036', url: 'https://go.wha.link/b8B1We' },
      { nombre: 'CHECKOUT BLACK ACCESS OFICIAL',            precio: 'Ver link', url: 'https://synergyunlimited.com/' },
    ],
  },
  {
    titulo: 'México · Black Access',
    items: [
      { nombre: 'LINKS MÉXICO BLACK',               precio: '$36,997 MXN', url: 'https://www.synergyforeducation.com/offers/bEcVEwrw' },
      { nombre: 'LINKS MÉXICO BLACK · Pase Doble',  precio: '$55,497 MXN', url: 'https://www.synergyforeducation.com/offers/SkQRGRbe' },
      { nombre: 'A MESES',                          precio: '$42,916 MXN', url: 'https://buy.stripe.com/eVq28s5wo4k28fgetg7Rk1e' },
      { nombre: 'A MESES · Pase Doble',             precio: '$64,376 MXN', url: 'https://buy.stripe.com/7sY00k9MEg2K3Z01Gu7Rk1f' },
      { nombre: 'APARTADO CONTADO',                 precio: '$9,999 MXN',  url: 'https://www.synergyforeducation.com/offers/QW4bS32r' },
      { nombre: 'APARTADO CONTADO · Pase Doble',    precio: '$15,999 MXN', url: 'https://www.synergyforeducation.com/offers/nMxUDpQp' },
      { nombre: 'APARTADO A MESES',                 precio: '$11,599 MXN', url: 'https://buy.stripe.com/9B6cN68IAaIq8fgcl87Rk1g' },
      { nombre: 'APARTADO A MESES · Pase Doble',    precio: '$18,558 MXN', url: 'https://buy.stripe.com/7sYeVebUMdUCgLMgBo7Rk1h' },
    ],
  },
  {
    titulo: 'México · General y VIP',
    items: [
      { nombre: 'GENERAL CONTADO PAUTA', precio: '$5,997 MXN', url: 'https://www.synergyforeducation.com/offers/sHf5tG7W' },
      { nombre: 'GENERAL MESES PAUTA',   precio: '$6,837 MXN', url: 'https://buy.stripe.com/5kQcN69ME7we6783OC7Rk1i' },
      { nombre: 'GENERAL CONTADO CLUB',  precio: '$3,997 MXN', url: 'https://www.synergyforeducation.com/offers/Q4LogqdV' },
      { nombre: 'GENERAL MESES CLUB',    precio: '$4,556 MXN', url: 'https://buy.stripe.com/dRmcN65wo6sa5345WK7Rk1j' },
      { nombre: 'VIP CONTADO PAUTA',     precio: '$7,997 MXN', url: 'https://www.synergyforeducation.com/offers/8dLZZrus' },
      { nombre: 'VIP MESES PAUTA',       precio: '$9,116 MXN', url: 'https://buy.stripe.com/eVqdRa2kc4k20MOad07Rk1k' },
      { nombre: 'VIP CONTADO CLUB',      precio: '$5,997 MXN', url: 'https://www.synergyforeducation.com/offers/vFAPaM3B' },
      { nombre: 'VIP MESES CLUB',        precio: '$6,836 MXN', url: 'https://buy.stripe.com/6oU8wQ6As2bU7bc0Cq7Rk1l' },
    ],
  },
  {
    titulo: 'México · Centurion',
    items: [
      { nombre: 'CENTURION CONTADO',               precio: '$90,000 MXN',  url: 'https://www.synergyforeducation.com/offers/VoBDAjgW' },
      { nombre: 'CENTURION A MESES',                precio: '$104,000 MXN', url: 'https://buy.stripe.com/bJedRacYQ6sa9jk0Cq7Rk1m' },
      { nombre: 'CENTURION CONTADO DOBLE',          precio: '$144,000 MXN', url: 'https://www.synergyforeducation.com/offers/wfLpTKeQ' },
      { nombre: 'CENTURION A MESES DOBLE',          precio: '$167,000 MXN', url: 'https://buy.stripe.com/14AbJ2bUM3fY8fg84S7Rk1n' },
      { nombre: 'ABONO CENTURION CONTADO',          precio: '$55,997 MXN', url: 'https://www.synergyforeducation.com/offers/LJtVB2Dm' },
      { nombre: 'ABONO CENTURION A MESES',          precio: '$64,997 MXN', url: 'https://buy.stripe.com/dRm5kEcYQ4k2cvwgBo7Rk1o' },
      { nombre: 'ABONO CENTURION DOBLE CONTADO',    precio: '$91,997 MXN', url: 'https://www.synergyforeducation.com/offers/tPTU7xdQ' },
      { nombre: 'ABONO CENTURION DOBLE A MESES',    precio: '$106,716 MXN', url: 'https://buy.stripe.com/8x228s2kcaIqeDE5WK7Rk1p' },
    ],
  },
  {
    titulo: 'USA',
    items: [
      { nombre: 'BLACK ACCESS CONTADO Y A MESES',              precio: '$1,997 USD', url: 'https://www.synergyforeducation.com/offers/ttDoMbie' },
      { nombre: 'BLACK ACCESS CONTADO Y A MESES · Pase Doble', precio: '$2,997 USD', url: 'https://www.synergyforeducation.com/offers/5Frzbkfk' },
      { nombre: 'BLACK ACCESS CONTADO Y A MESES · Apartado',   precio: '$499 USD',   url: 'https://www.synergyforeducation.com/offers/rE7ZWZea' },
      { nombre: 'BLACK ACCESS CONTADO Y A MESES · Apartado',   precio: '$799 USD',   url: 'https://www.synergyforeducation.com/offers/BKZNFA2P' },
      { nombre: 'GENERAL CONTADO PAUTA',  precio: '$297 USD',   url: 'https://www.synergyforeducation.com/offers/oyzBqqCj' },
      { nombre: 'GENERAL CONTADO CLUB',   precio: '$197 USD',   url: 'https://www.synergyforeducation.com/offers/uNJqZNRV' },
      { nombre: 'VIP CONTADO PAUTA',      precio: '$397 USD',   url: 'https://www.synergyforeducation.com/offers/cipSNDwV' },
      { nombre: 'VIP CONTADO CLUB',       precio: '$297 USD',   url: 'https://www.synergyforeducation.com/offers/4x5wRKH4' },
      { nombre: 'CENTURION CONTADO',      precio: '$4,997 USD', url: 'https://www.synergyforeducation.com/offers/rdpUDkve' },
      { nombre: 'CENTURION DOBLE CONTADO', precio: '$7,997 USD', url: 'https://www.synergyforeducation.com/offers/LA9tfSqF' },
      { nombre: 'ABONO CENTURION CONTADO', precio: '$3,000 USD', url: 'https://www.synergyforeducation.com/offers/2muzVugM' },
      { nombre: 'ABONO CENTURION DOBLE CONTADO', precio: '$5,000 USD', url: 'https://www.synergyforeducation.com/offers/ry6JizC2' },
    ],
  },
  {
    titulo: 'LATAM',
    items: [
      { nombre: 'LINKS LATAM',              precio: 'Ver link', url: 'https://pay.hotmart.com/Q106162772V?off=5o7ja6fi' },
      { nombre: 'LINKS LATAM · Pase Doble', precio: 'Ver link', url: 'https://pay.hotmart.com/O106162861G?off=y0uogpak' },
    ],
  },
]

/* ─── Links de pago ─────────────────────────────────────────────────────── */
export const WEBINARS_LINKS: Subseccion[] = [
  {
    titulo: 'Links USA',
    items: [
      { nombre: 'Landing de métodos de pago',  precio: 'Ver link', url: 'https://synergyforeducation.mx/metodos-de-pago-seed-usa-presencial' },
      { nombre: 'PAGO CLUB TOTAL',        precio: '$1,499.00', url: 'https://www.synergyforeducation.com/offers/r7RycGhZ/checkout' },
      { nombre: 'APARTADO 100',           precio: '$100.00',   url: 'https://buy.stripe.com/aEU8ynfpzeiNgjS02G' },
      { nombre: 'APARTADO 200',           precio: '$200.00',   url: 'https://buy.stripe.com/fZeg0P4KV2A52t203Vu' },
      { nombre: 'APARTADO 500',           precio: '$500.00',   url: 'https://buy.stripe.com/4gw7uj7X75Mh6Ji6sl' },
      { nombre: 'APARTADO 600',           precio: '$600.00',   url: 'https://buy.stripe.com/8wMcP8230aZCds416t' },
      { nombre: 'RESTANTE APARTADO 200',  precio: '$799.00',   url: 'https://www.synergyforeducation.com/offers/iUsLucxF' },
      { nombre: 'RESTANTE APARTADO 300',  precio: '$699.00',   url: 'https://www.synergyforeducation.com/offers/2WoBNigS' },
      { nombre: 'RESTANTE APARTADO 500',  precio: '$499.00',   url: 'https://buy.stripe.com/fZe4iC3746Jm9bOcNH' },
      { nombre: 'RESTANTE APARTADO 600',  precio: '$399.00',   url: 'https://buy.stripe.com/5kA7uj5OZb6B5Fe04L' },
      { nombre: 'RESTANTE APARTADO 700',  precio: '$299.00',   url: 'https://buy.stripe.com/28o5mb91beiN8RqdTV' },
      { nombre: 'RESTANTE APARTADO 250',  precio: '$749.00',   url: 'https://www.synergyforeducation.com/offers/mgU4zE5J' },
      { nombre: 'APARTADO CLUB',          precio: '$1,000.00', url: 'https://www.synergyforeducation.com/offers/L2k7GaAe' },
      { nombre: 'APARTADO CLUB',          precio: '$1,099.00', url: 'https://www.synergyforeducation.com/offers/sSzD4m3A' },
      { nombre: 'APARTADO CLUB',          precio: '$1,350.00', url: 'https://www.synergyforeducation.com/offers/Jvv7s3ny' },
      { nombre: 'APARTADO CLUB',          precio: '$1,299.00', url: 'https://www.synergyforeducation.com/offers/i4wSPCza' },
      { nombre: 'APARTADO CLUB',          precio: '$1,199.00', url: 'https://www.synergyforeducation.com/offers/vogAoJDV' },
      { nombre: 'APARTADO CLUB',          precio: '$499.00',   url: 'https://www.synergyforeducation.com/offers/vLAoDsKD' },
      { nombre: 'APARTADO CLUB',          precio: '$600.00',   url: 'https://www.synergyforeducation.com/offers/VffXyNPT' },
      { nombre: 'APARTADO CLUB',          precio: '$899.00',   url: 'https://www.synergyforeducation.com/offers/Bv8pGzFC' },
    ],
  },
  {
    titulo: 'Webinar',
    items: [
      { nombre: 'Pago Club Total',            precio: '$999' },
      { nombre: 'Pago Club Total (anterior)', precio: '$799',  url: 'https://buy.stripe.com/28o8yS7nkaZC4VyfZQ' },
      { nombre: 'Apartado $100',              precio: '$100',  url: 'https://buy.stripe.com/aEU8ynfpzeiNgjS02G' },
      { nombre: 'Apartado $200',              precio: '$200',  url: 'https://buy.stripe.com/fZeg0P4KV2A52t203V' },
      { nombre: 'Apartado $250',              precio: '$250',  url: 'https://www.synergyforeducation.com/offers/e2qyLS6j' },
      { nombre: 'Apartado $300',              precio: '$300',  url: 'https://buy.stripe.com/4gw5mbcdndeJebK9Ff' },
      { nombre: 'Apartado $350',              precio: '$350' },
      { nombre: 'Apartado $400',              precio: '$400',  url: 'https://buy.stripe.com/bIY8yngtD6QlebKdVR' },
      { nombre: 'Apartado $450',              precio: '$450' },
      { nombre: 'Apartado $500',              precio: '$500',  url: 'https://buy.stripe.com/4gw7uj7X75Mh6Ji6sl' },
      { nombre: 'Apartado $600',              precio: '$600' },
    ],
  },
  {
    titulo: 'Presenciales México',
    items: [
      { nombre: 'LANDING CON RESUMEN DE TODO',           precio: 'Ver link', url: 'https://synergyforeducation.mx/metodos-de-pago-seed-mdl-2612-405502' },
      { nombre: 'PAGO CLUB TOTAL DE CONTADO 3 MESES',    precio: '$9,997',  url: 'https://www.synergyforeducation.com/offers/pZabs8XY/checkout' },
      { nombre: 'PAGO CLUB TOTAL 3 MESES A MESES',       precio: '$11,397', url: 'https://buy.stripe.com/fZu7sM6As9Embrs4SG7Rj2J' },
      { nombre: 'PAGO CLUB TOTAL DE CONTADO 6 MESES',    precio: '$12,997', url: 'https://www.synergyforeducation.com/offers/vMzthz2s/checkout' },
      { nombre: 'PAGO CLUB TOTAL 6 MESES A MESES',       precio: '$14,817', url: 'https://buy.stripe.com/bJeeVecYQ9Emano84S7Rj2F' },
      { nombre: 'PAGO CLUB TOTAL DE CONTADO 12 MESES',   precio: '$14,997', url: 'https://www.synergyforeducation.com/offers/SuxLQPiC/checkout' },
      { nombre: 'PAGO CLUB TOTAL 12 MESES A MESES',      precio: '$17,097', url: 'https://buy.stripe.com/dRmfZiaQI5o6fHIetg7Rj2K' },
      { nombre: 'RESTANTE CLUB DE CONTADO',              precio: '$7,997',  url: 'https://www.synergyforeducation.com/offers/LfjzEzGF' },
      { nombre: 'RESTANTE CLUB A MESES',                 precio: '$9,116',  url: 'https://buy.stripe.com/6oE6qf7X7fmRebKe3O' },
      { nombre: 'RESTANTE',                              precio: '$3,999',  url: 'https://www.synergyforeducation.com/offers/tiNNmTXi' },
      { nombre: 'APARTADO CLUB CONTADO',                 precio: '$2,000',  url: 'https://www.synergyforeducation.com/offers/7mw2rFz3' },
      { nombre: 'Restante Club Sinergético de contado',  precio: '$4,497',  url: 'https://buy.stripe.com/eVqfZigb2dUC7bc1Gu7Rj1o' },
      { nombre: 'Restante Club Sinergetico de contado',  precio: '$4,997',  url: 'https://buy.stripe.com/00w6oIbUMbMucvw70O7Ri0F' },
      { nombre: 'VIP PRESENCIALES NOV',                  precio: '$1,000' },
      { nombre: 'Restante Club Sinergetico a meses',     precio: '$5,597',  url: 'https://buy.stripe.com/aFa28s4sk3fYbrsfxk7Rh1g' },
    ],
  },
  {
    titulo: 'Renovación Club Sinergético',
    items: [
      { nombre: 'RENOVACIÓN MX LINK ANTES', precio: '$5,396.00', url: 'https://pay.hotmart.com/Y99824146R?off=ckc0y9q3&bid=1748027679564' },
      { nombre: 'RENOVACION MX 1 año',      precio: '$5,997.00', url: 'https://checkout.synergyforeducation.com/pay/pl_d5a368bddbdd56eac7c049c65fe3d6c9' },
      { nombre: 'RENOVACION LATAM 1 año',   precio: '$299.00',   url: 'https://pay.hotmart.com/D106300176V?off=ill2992e' },
      { nombre: 'RENOVACION USA 1 año',     precio: '$999.00',   url: 'https://www.synergyforeducation.com/offers/hAH7JZbL' },
      { nombre: 'OXXO (Emergencias)',  precio: '$1,000', url: 'https://mpago.li/1ykFsjZ' },
      { nombre: 'OXXO (Emergencias)',  precio: '$1,500', url: 'https://mpago.li/2w7ZW4c' },
    ],
  },
  {
    titulo: 'Repitch Club Sinergético',
    items: [
      { nombre: 'Repitch MX · 3 Meses',    precio: '$5,997', url: 'https://pay.hotmart.com/M101848244V?checkoutMode=10' },
      { nombre: 'Repitch LATAM · 3 Meses', precio: '$299',   url: 'https://pay.hotmart.com/B99463683H?checkoutMode=10' },
      { nombre: 'Repitch USA · 3 Meses',   precio: '$999',   url: 'https://www.synergyforeducation.com/offers/qVezpFYZ' },
    ],
  },
  {
    titulo: 'Upgrades / Renovar Club Sinergético LIVE',
    items: [
      { nombre: 'MX 3M extras Cambia a 2k', precio: '$2,000.00', url: 'https://pay.hotmart.com/D103381825X?off=1qewqn8n&checkoutMode=10' },
      { nombre: 'MX 12M UPGRADE',           precio: '$4,000.00', url: 'https://pay.hotmart.com/D103381825X?off=sbq3ji19&checkoutMode=10' },
      { nombre: 'MX 12M UPGRADE',           precio: '$6,000.00', url: 'https://buy.stripe.com/5kQ8wQ0c4cQy2UW98W7Rk1U' },
      { nombre: 'LATAM 3M extras',          precio: '$50.00',    url: 'https://pay.hotmart.com/W10325522U?off=l7mfo7ms&checkoutMode=10' },
      { nombre: 'LATAM 12M UPGRADE',        precio: '$100.00',   url: 'https://pay.hotmart.com/E106300427A?off=c79ny8c0' },
      { nombre: 'US 3M extras $ 200',       precio: '$200.00',   url: 'https://www.synergyforeducation.com/offers/kzoXLXk3' },
      { nombre: 'US 12M UPGRADE',           precio: '$300.00',   url: 'https://www.synergyforeducation.com/offers/E9xNErzt' },
    ],
  },
]

export const PRESENCIALES: Subseccion[] = [
  {
    titulo: 'Webinar LATAM Centro · Miércoles 7 pm CDMX',
    items: [
      { nombre: 'Renovación MX 1 año',    precio: '$5,997', url: 'https://checkout.synergyforeducation.com/pay/pl_d5a368bddbdd56eac7c049c65fe3d6c9' },
      { nombre: 'Renovación LATAM 1 año', precio: '$299',  url: 'https://pay.hotmart.com/D106300176V' },
      { nombre: 'Renovación USA 1 año',   precio: '$999',   url: 'https://synergyforeducation.com/offers/hAH7JZbL' },
      { nombre: 'LINK PAGO VIP',          precio: 'Ver link', url: 'https://pay.hotmart.com/G102993630L?checkoutMode=10' },
      { nombre: 'METODOS DE PAGO',        precio: 'Ver link', url: 'https://synergyforeducation.lat/metodo-de-pago-seed-js-latam-centro' },
      { nombre: 'TOTAL CS + 1 AÑO',       precio: '$499.00', url: 'https://pay.hotmart.com/L103011342R?checkoutMode=10' },
      { nombre: 'TOTAL CS + 6 MESES',     precio: '$399.00', url: 'https://pay.hotmart.com/H103011204K?checkoutMode=10&bid=1763581833605' },
      { nombre: 'TOTAL CS + 3 MESES',     precio: '$299.00', url: 'https://pay.hotmart.com/S103010970N?checkoutMode=10&bid=1763581817139' },
      { nombre: 'APARTADO JS',            precio: '$449.00', url: 'https://pay.hotmart.com/J99418304L?off=p019ko3x&checkoutMode=10' },
      { nombre: 'APARTADO JS',            precio: '$349.00', url: 'https://pay.hotmart.com/J99418304L?off=t1bcwc65&checkoutMode=10' },
      { nombre: 'PAGO CLUB TOTAL JS',     precio: '$299.00', url: 'https://pay.hotmart.com/J99414849Q?off=jxflzvvx&checkoutMode=10' },
      { nombre: 'APARTADO JS',            precio: '$249.00', url: 'https://pay.hotmart.com/J99418304L?checkoutMode=10&bid=1757695904759' },
      { nombre: 'APARTADO JS',            precio: '$200.00', url: 'https://pay.hotmart.com/J99418304L?off=068q8s6x&checkoutMode=10' },
      { nombre: 'APARTADO JS 50%',        precio: '$150.00', url: 'https://pay.hotmart.com/J99418304L?off=mryaw4ho&checkoutMode=10' },
      { nombre: 'APARTADO JS',            precio: '$100.00', url: 'https://pay.hotmart.com/J99418304L?off=7kpchuep&checkoutMode=10' },
      { nombre: 'APARTADO JS',            precio: '$50.00',  url: 'https://pay.hotmart.com/J99418304L?off=6rb6t05u&checkoutMode=10' },
      { nombre: 'APARTADO JS',            precio: '$25.00',  url: 'https://pay.hotmart.com/J99418304L?off=kvxegjrs&checkoutMode=10' },
    ],
  },
  {
    titulo: 'Webinar México JS Jorge · Jueves 8 pm CDMX',
    items: [
      { nombre: 'TOTAL CS + 1 AÑO',  precio: '$11,997.00', url: 'https://pay.hotmart.com/X102928391G?checkoutMode=10&bid=1763076772885' },
      { nombre: 'TOTAL CS + 1 AÑO',  precio: '$9,997.00',  url: 'https://pay.hotmart.com/X102928391G?off=b2hyykdv&checkoutMode=10' },
      { nombre: 'TOTAL CS + 6 MESES', precio: '$9,997.00',  url: 'https://pay.hotmart.com/H102927920X?checkoutMode=10&bid=1763076489452' },
      { nombre: 'TOTAL CS + 6 MESES', precio: '$7,997.00',  url: 'https://pay.hotmart.com/H102927920X?off=5tkt1ozb&checkoutMode=10' },
      { nombre: 'TOTAL CS + 3 MESES', precio: '$5,997.00',  url: 'https://pay.hotmart.com/H102927830R?checkoutMode=10&bid=1763076189360' },
      { nombre: 'APARTADO JS',       precio: '$8,997.00',  url: 'https://pay.hotmart.com/J99418451H?off=lxte4e8o&checkoutMode=10' },
      { nombre: 'APARTADO JS',       precio: '$6,997.00',  url: 'https://pay.hotmart.com/J99418451H?off=15tikd9h&checkoutMode=10' },
      { nombre: 'APARTADO JS',       precio: '$5,497.00',  url: 'https://pay.hotmart.com/J99418451H?checkoutMode=10' },
      { nombre: 'APARTADO JS',       precio: '$4,997.00',  url: 'https://pay.hotmart.com/J99418451H?off=pbybumtz&checkoutMode=10' },
      { nombre: 'APARTADO JS',       precio: '$4,497.00',  url: 'https://pay.hotmart.com/J99418451H?off=5sntpt8d&checkoutMode=10' },
      { nombre: 'APARTADO JS',       precio: '$3,997.00',  url: 'https://pay.hotmart.com/J99418451H?off=bj7chyev&checkoutMode=10' },
      { nombre: 'APARTADO JS',       precio: '$3,500.00',  url: 'https://pay.hotmart.com/J99418451H?off=0x8583dq&checkoutMode=10' },
      { nombre: 'APARTADO JS 50%',   precio: '$3,000.00',  url: 'https://pay.hotmart.com/J99418451H?off=3bhawz7g&checkoutMode=10' },
      { nombre: 'APARTADO JS',       precio: '$2,500.00',  url: 'https://pay.hotmart.com/J99418451H?off=p0cox4i6&checkoutMode=10' },
      { nombre: 'APARTADO JS',       precio: '$2,000.00',  url: 'https://pay.hotmart.com/J99418451H?off=ddduwy6j&checkoutMode=10' },
      { nombre: 'APARTADO JS',       precio: '$1,500.00',  url: 'https://pay.hotmart.com/J99418451H?off=vdrtl02t&checkoutMode=10' },
      { nombre: 'APARTADO JS',       precio: '$1,000.00',  url: 'https://pay.hotmart.com/J99418451H?off=7sb0r4ys&checkoutMode=10' },
      { nombre: 'APARTADO JS',       precio: '$500.00',    url: 'https://pay.hotmart.com/J99418451H?off=a6c9susk&checkoutMode=10' },
    ],
  },
  {
    titulo: 'Webinar México Manuel · Martes 8 pm CDMX',
    items: [
      { nombre: 'TOTAL CS + 1 AÑO',   precio: '$11,997.00', url: 'https://pay.hotmart.com/A102653279Q?checkoutMode=10&bid=1761691506586' },
      { nombre: 'TOTAL CS + 1 AÑO',   precio: '$9,997.00',  url: 'https://pay.hotmart.com/A102653279Q?off=c50q26u6&checkoutMode=10' },
      { nombre: 'TOTAL CS + 6 MESES', precio: '$9,997.00',  url: 'https://pay.hotmart.com/A102653195W?checkoutMode=10' },
      { nombre: 'TOTAL CS + 6 MESES', precio: '$7,997.00',  url: 'https://pay.hotmart.com/A102653195W?off=wsxlnabt&checkoutMode=10' },
      { nombre: 'TOTAL CS + 3 MESES', precio: '$5,997.00',  url: 'https://pay.hotmart.com/V99414167H?checkoutMode=10&bid=1761691259153' },
      { nombre: 'APARTADO JS',        precio: '$8,997.00',  url: 'https://pay.hotmart.com/N99414326Q?off=sgya10ld&checkoutMode=10' },
      { nombre: 'APARTADO JS',        precio: '$6,997.00',  url: 'https://pay.hotmart.com/N99414326Q?off=p8kksf5k&checkoutMode=10' },
      { nombre: 'APARTADO MDL',       precio: '$5,497.00',  url: 'https://pay.hotmart.com/N99414326Q?off=r7f11olx' },
      { nombre: 'APARTADO MDL',       precio: '$4,997.00',  url: 'https://pay.hotmart.com/N99414326Q?off=ds2occzx' },
      { nombre: 'APARTADO MDL',       precio: '$4,497.00',  url: 'https://pay.hotmart.com/N99414326Q?off=wug3ggkm' },
      { nombre: 'APARTADO MDL',       precio: '$3,997.00',  url: 'https://pay.hotmart.com/N99414326Q?off=dw6kt18b' },
      { nombre: 'APARTADO MDL',       precio: '$3,500.00',  url: 'https://pay.hotmart.com/N99414326Q?off=m5po9ixj' },
      { nombre: 'APARTADO MDL 50%',   precio: '$3,000.00',  url: 'https://pay.hotmart.com/N99414326Q?off=4xepyp3z' },
      { nombre: 'APARTADO MDL',       precio: '$2,500.00',  url: 'https://pay.hotmart.com/N99414326Q?off=f50ktwdg' },
      { nombre: 'APARTADO MDL',       precio: '$2,000.00',  url: 'https://pay.hotmart.com/N99414326Q?off=jeefe0wn' },
      { nombre: 'APARTADO MDL',       precio: '$1,500.00',  url: 'https://pay.hotmart.com/N99414326Q?off=lrn731z8' },
      { nombre: 'APARTADO MDL',       precio: '$1,000.00',  url: 'https://pay.hotmart.com/N99414326Q?off=1tu43oi9' },
      { nombre: 'APARTADO MDL',       precio: '$500.00',    url: 'https://pay.hotmart.com/N99414326Q?off=a81ua6iz' },
    ],
  },
  {
    titulo: 'Webinar USA JS · Miércoles 7/8 pm CDMX',
    items: [
      { nombre: 'METODOS DE PAGO',    precio: 'Ver link', url: 'https://synergyforeducation.us/metodo-de-pago-seed-js-usa-west' },
      { nombre: 'TOTAL CS + 1 AÑO',   precio: '$1,499.00', url: 'https://www.synergyforeducation.com/offers/jQFm9RkR' },
      { nombre: 'TOTAL CS + 6 MESES', precio: '$1,299.00', url: 'https://www.synergyforeducation.com/offers/oSE8ue2f' },
      { nombre: 'TOTAL CS + 3 MESES', precio: '$999.00',   url: 'https://www.synergyforeducation.com/offers/Yr6542WB' },
      { nombre: 'APARTADO JS',        precio: '$1,399.00', url: 'https://www.synergyforeducation.com/offers/LMLFRXkq' },
      { nombre: 'APARTADO JS',        precio: '$1,199.00', url: 'https://www.synergyforeducation.com/offers/2tY7Mxi2' },
      { nombre: 'APARTADO JS',        precio: '$1,099.00', url: 'https://www.synergyforeducation.com/offers/bgZm4ojy' },
      { nombre: 'APARTADO JS',        precio: '$899.00',   url: 'https://www.synergyforeducation.com/offers/nXLEcgd7' },
      { nombre: 'APARTADO JS',        precio: '$799.00',   url: 'https://www.synergyforeducation.com/offers/vojc66EK' },
      { nombre: 'APARTADO JS',        precio: '$699.00',   url: 'https://www.synergyforeducation.com/offers/wyG8bMVG' },
      { nombre: 'APARTADO JS',        precio: '$599.00',   url: 'https://www.synergyforeducation.com/offers/vzM5Xz2F' },
      { nombre: 'APARTADO JS',        precio: '$500.00',   url: 'https://www.synergyforeducation.com/offers/Tkkv6p2e' },
      { nombre: 'APARTADO JS',        precio: '$400.00',   url: 'https://www.synergyforeducation.com/offers/sgV2dU46' },
      { nombre: 'APARTADO JS',        precio: '$300.00',   url: 'https://www.synergyforeducation.com/offers/N2hbor9L' },
      { nombre: 'APARTADO JS',        precio: '$250.00',   url: 'https://www.synergyforeducation.com/offers/pyJUgAbc' },
      { nombre: 'APARTADO JS',        precio: '$200.00',   url: 'https://www.synergyforeducation.com/offers/CHzWmu2H' },
      { nombre: 'APARTADO JS',        precio: '$150.00',   url: 'https://www.synergyforeducation.com/offers/YsfEhB2s' },
      { nombre: 'APARTADO JS',        precio: '$100.00',   url: 'https://www.synergyforeducation.com/offers/M8u3odsh' },
      { nombre: 'APARTADO JS',        precio: '$50.00',    url: 'https://www.synergyforeducation.com/offers/T2fspUEF' },
    ],
  },
  {
    titulo: 'Europa Webinar JS · Sábado 10 am CDMX',
    items: [
      { nombre: 'LANDING OFERTA',         precio: '$499.00', url: 'https://synergyforeducation.us/oferta-seed-eur-evg-js' },
      { nombre: 'PAGO CLUB TOTAL JS EUR',  precio: '$499.00', url: 'https://pay.hotmart.com/M99950911U?off=fsbdkkcu' },
      { nombre: 'APARTADO MDL',           precio: '$449.00', url: 'https://pay.hotmart.com/M99950911U?off=fsbdkkcu' },
      { nombre: 'APARTADO MDL',           precio: '$399.00', url: 'https://pay.hotmart.com/X99954094J?off=dzhi5aku' },
      { nombre: 'APARTADO MDL',           precio: '$349.00', url: 'https://pay.hotmart.com/X99954094J?off=t45w97vr' },
      { nombre: 'APARTADO MDL',           precio: '$299.00', url: 'https://pay.hotmart.com/X99954094J?off=qu6dmes1' },
      { nombre: 'APARTADO JS 50%',        precio: '$250.00', url: 'https://pay.hotmart.com/X99954094J?off=oq42ygsq' },
      { nombre: 'APARTADO MDL',           precio: '$150.00', url: 'https://pay.hotmart.com/X99954094J?off=3nxqw8ti' },
      { nombre: 'APARTADO MDL',           precio: '$100.00', url: 'https://pay.hotmart.com/X99954094J?off=x5o326oa' },
      { nombre: 'APARTADO MDL',           precio: '$50.00',  url: 'https://pay.hotmart.com/X99954094J?off=ycflh2ao' },
    ],
  },
  {
    titulo: 'USA Webinar MDL · Jueves 6 pm CDMX',
    items: [
      { nombre: 'LANDING OFERTA',           precio: '$999.00', url: 'https://www.synergyforeducation.com/offers/4Ec94KJY' },
      { nombre: 'PAGO CLUB TOTAL JS USA',    precio: '$999.00', url: 'https://www.synergyforeducation.com/offers/REEUiC9n' },
      { nombre: 'APARTADO MDL',             precio: '$899.00', url: 'https://www.synergyforeducation.com/offers/828B42Em' },
      { nombre: 'APARTADO MDL',             precio: '$799.00', url: 'https://www.synergyforeducation.com/offers/Fpqq3FHC' },
      { nombre: 'APARTADO MDL',             precio: '$699.00', url: 'https://www.synergyforeducation.com/offers/62NLVcov' },
      { nombre: 'APARTADO MDL',             precio: '$599.00', url: 'https://www.synergyforeducation.com/offers/dfvLAAJ4' },
      { nombre: 'APARTADO JS 50%',          precio: '$500.00', url: 'https://www.synergyforeducation.com/offers/deq6wyMN' },
      { nombre: 'APARTADO MDL',             precio: '$400.00', url: 'https://www.synergyforeducation.com/offers/xKufwRzJ' },
      { nombre: 'APARTADO MDL',             precio: '$300.00', url: 'https://www.synergyforeducation.com/offers/EDzMgoHK' },
      { nombre: 'APARTADO MDL',             precio: '$250.00', url: 'https://www.synergyforeducation.com/offers/moNrRcW3' },
      { nombre: 'APARTADO MDL',             precio: '$200.00', url: 'https://www.synergyforeducation.com/offers/VoQ9zmwj' },
      { nombre: 'APARTADO MDL',             precio: '$150.00', url: 'https://www.synergyforeducation.com/offers/DzFdopPQ' },
      { nombre: 'APARTADO MDL',             precio: '$100.00', url: 'https://www.synergyforeducation.com/offers/uv45y2Fh' },
      { nombre: 'APARTADO MDL',             precio: '$50.00',  url: 'https://www.synergyforeducation.com/offers/dh5FT6Ka' },
      { nombre: 'AP. CON ACCESO JS 50%',    precio: '$499.00', url: 'https://www.synergyforeducation.com/offers/rPTtcLsn' },
      { nombre: '4 PAGOS DE 150 USD',       precio: '$150.00', url: 'https://www.synergyforeducation.com/offers/babcoTn2' },
    ],
  },
  {
    titulo: 'Checkout LATAM Centro',
    items: [
      { nombre: '299 USA', precio: '$299 USD', url: 'https://checkout.synergyforeducation.com/pay/pl_e4f952b29fb41546797f6281c447c91f' },
      { nombre: '399 USA', precio: '$399 USD', url: 'https://checkout.synergyforeducation.com/pay/pl_d94118d2504d8de41faebc7098dd23e2' },
      { nombre: '499 USA', precio: '$499 USD', url: 'https://checkout.synergyforeducation.com/pay/pl_139ed0991655dc08ed14a20be2f4daca' },
    ],
  },
  {
    titulo: 'Webinar Manuel MX Revolución IA · Martes 8 pm CDMX',
    items: [
      { nombre: 'TOTAL LEGENDAR IA',     precio: '$5,997.00', url: 'https://checkout.synergyforeducation.com/pay/pl_43aafece8aa3b645e8a4c93e6f156f3b' },
      { nombre: 'CS TOTAL LEGENDAR IA',  precio: '$3,997.00', url: 'https://checkout.synergyforeducation.com/pay/pl_43aafece8aa3b645e8a4c93e6f156f3b' },
      { nombre: 'APARTADO MDL IA 50%',   precio: '$3,000.00', url: 'https://checkout.synergyforeducation.com/pay/pl_2e1adf756bb9797429e7a5848a5dbda3' },
      { nombre: 'APARTADO MDL IA',       precio: '$2,000.00', url: 'https://checkout.synergyforeducation.com/pay/pl_e7fa50c588635ebae00133d2e9c51195' },
      { nombre: 'APARTADO MDL IA',       precio: '$1,000.00', url: 'https://checkout.synergyforeducation.com/pay/pl_dd35c5d7d56708b17602bbabb9c34cc8' },
    ],
  },
]
