// Devoluciones nuevas encontradas en los exports directos de Stripe subidos
// a Documentos/reembolsos el 8 de septiembre de 2026 (llc 8 sep.csv, stripe
// de contado.csv, stripe meses 8sep.csv) — ninguno de estos IDs de operación
// existía ya en IMPORT_DISPUTAS_2026 ni en IMPORT_REEMBOLSOS_DOCS_2026.
// Cada registro lleva importId para no duplicarse si el botón se usa más de
// una vez. El número de operación es el ID de cargo/pago real de Stripe
// (columna "id" del export).
// El campo 'resultado' sale de comparar Amount vs Amount Refunded: si son
// iguales -> completo, si Amount Refunded es menor -> parcial. El monto
// registrado es siempre el Amount Refunded (lo que realmente se devolvió),
// en la moneda original del cargo (no la convertida).
// El campo 'acceso' se dejó en 'activo' por defecto porque el export no
// indica el estado de acceso real — hay que revisarlo a mano.
export const IMPORT_REEMBOLSOS_SEP_2026 = [
  // ── llc 8 sep.csv (Statement Descriptor: SINERGETICOS LLC) ──
  {"evento":"WUSA","mes":"2026-09","plataforma":"Stripe LLC","fechaDevolucion":"2026-09-05","monto":500,"divisa":"USD","correo":"","producto":"Otro","productoDetalle":"mmpos_In-Person; x1 Purchase","acceso":"activo","banco":"Otro","bancoDetalle":"","numeroTarjeta":"","numeroOperacion":"ch_3U7hDoIf6tuQTC642brZVkzh","notas":"⚠️ Verificar acceso manualmente. Importado de export directo Stripe (Stripe LLC).","costoEmpresa":0,"costoEmpresaDivisa":"MXN","resultado":"completo"},
  {"evento":"WUSA","mes":"2026-09","plataforma":"Stripe LLC","fechaDevolucion":"2026-09-05","monto":500,"divisa":"USD","correo":"","producto":"Otro","productoDetalle":"mmpos_In-Person; x1 Purchase","acceso":"activo","banco":"Otro","bancoDetalle":"","numeroTarjeta":"","numeroOperacion":"ch_3U7getIf6tuQTC642rhZI51B","notas":"⚠️ Verificar acceso manualmente. Importado de export directo Stripe (Stripe LLC).","costoEmpresa":0,"costoEmpresaDivisa":"MXN","resultado":"completo"},
  {"evento":"WUSA","mes":"2026-08","plataforma":"Stripe LLC","fechaDevolucion":"2026-08-28","monto":1999,"divisa":"USD","correo":"","producto":"Club Sinergetico","productoDetalle":"mmpos_In-Person; x1 12M | CLUB SINERGETICO","acceso":"activo","banco":"Otro","bancoDetalle":"","numeroTarjeta":"","numeroOperacion":"ch_3U7g76If6tuQTC642tVRxdYX","notas":"⚠️ Verificar acceso manualmente. Importado de export directo Stripe (Stripe LLC).","costoEmpresa":0,"costoEmpresaDivisa":"MXN","resultado":"completo"},
  {"evento":"WUSA","mes":"2026-08","plataforma":"Stripe LLC","fechaDevolucion":"2026-08-28","monto":1497,"divisa":"USD","correo":"","producto":"Club Sinergetico","productoDetalle":"mmpos_In-Person; x1 3M | CLUB SINERGETICO","acceso":"activo","banco":"Otro","bancoDetalle":"","numeroTarjeta":"","numeroOperacion":"ch_3U7fvFIf6tuQTC642NWsdlZ5","notas":"⚠️ Verificar acceso manualmente. Importado de export directo Stripe (Stripe LLC).","costoEmpresa":0,"costoEmpresaDivisa":"MXN","resultado":"completo"},
  {"evento":"WUSA","mes":"2026-09","plataforma":"Stripe LLC","fechaDevolucion":"2026-09-05","monto":500,"divisa":"USD","correo":"","producto":"Apartado","productoDetalle":"mmpos_In-Person; x1 APARTADO CLUB","acceso":"activo","banco":"Otro","bancoDetalle":"","numeroTarjeta":"","numeroOperacion":"ch_3U7KFNIf6tuQTC641s4hJNax","notas":"⚠️ Verificar acceso manualmente. Importado de export directo Stripe (Stripe LLC).","costoEmpresa":0,"costoEmpresaDivisa":"MXN","resultado":"completo"},
  {"evento":"WUSA","mes":"2026-09","plataforma":"Stripe LLC","fechaDevolucion":"2026-09-02","monto":500,"divisa":"USD","correo":"","producto":"Otro","productoDetalle":"mmpos_In-Person; x1 Purchase","acceso":"activo","banco":"Otro","bancoDetalle":"","numeroTarjeta":"","numeroOperacion":"ch_3U6hzgIf6tuQTC640Dayj7My","notas":"⚠️ Verificar acceso manualmente. Importado de export directo Stripe (Stripe LLC).","costoEmpresa":0,"costoEmpresaDivisa":"MXN","resultado":"completo"},
  {"evento":"LEGENDAR-IA","mes":"2026-08","plataforma":"Stripe LLC","fechaDevolucion":"2026-08-20","monto":999,"divisa":"USD","correo":"","producto":"Legendar-IA","productoDetalle":"mmpos_In-Person; x1 LegendarIA","acceso":"activo","banco":"Otro","bancoDetalle":"","numeroTarjeta":"","numeroOperacion":"ch_3U6KkaIf6tuQTC641xkJSyip","notas":"⚠️ Verificar acceso manualmente. Importado de export directo Stripe (Stripe LLC).","costoEmpresa":0,"costoEmpresaDivisa":"MXN","resultado":"completo"},

  // ── stripe de contado.csv (Statement Descriptor: SINERGETICOS) ──
  {"evento":"PRES-MX","mes":"2026-08","plataforma":"Stripe Contado","fechaDevolucion":"2026-08-27","monto":2000,"divisa":"MXN","correo":"citla19877@gmail.com","producto":"Club Sinergetico","productoDetalle":"","acceso":"activo","banco":"Otro","bancoDetalle":"","numeroTarjeta":"","numeroOperacion":"py_3U8mUcF0tn7jOn010YmG7jGJ","notas":"⚠️ Verificar acceso manualmente. Importado de export directo Stripe (Stripe Contado).","costoEmpresa":0,"costoEmpresaDivisa":"MXN","resultado":"parcial"},
  {"evento":"PRES-MX","mes":"2026-08","plataforma":"Stripe Contado","fechaDevolucion":"2026-08-31","monto":20580,"divisa":"MXN","correo":"mbtd82@gmail.com","producto":"Club Sinergetico","productoDetalle":"","acceso":"activo","banco":"Otro","bancoDetalle":"","numeroTarjeta":"","numeroOperacion":"ch_3U6ESMF0tn7jOn010kEe1N61","notas":"⚠️ Verificar acceso manualmente. Importado de export directo Stripe (Stripe Contado).","costoEmpresa":0,"costoEmpresaDivisa":"MXN","resultado":"parcial"},
  {"evento":"PRES-MX","mes":"2026-08","plataforma":"Stripe Contado","fechaDevolucion":"2026-08-20","monto":5997,"divisa":"MXN","correo":"elchimegrill@gmail.com","producto":"Otro","productoDetalle":"PASE GENERAL SYNERGY ULIMITED MX 2026","acceso":"activo","banco":"Otro","bancoDetalle":"","numeroTarjeta":"","numeroOperacion":"ch_3U63NuF0tn7jOn0107VF8LKX","notas":"⚠️ Verificar acceso manualmente. Importado de export directo Stripe (Stripe Contado).","costoEmpresa":0,"costoEmpresaDivisa":"MXN","resultado":"completo"},
  {"evento":"PRES-MX","mes":"2026-07","plataforma":"Stripe Contado","fechaDevolucion":"2026-07-29","monto":1500,"divisa":"MXN","correo":"e.sosa.r@live.com.mx","nombre":"Enrique Sosa Rodríguez","telefono":"6566384185","producto":"Otro","productoDetalle":"Cd. Juárez | 11 de Agosto | 6:00 pm - Pase Doble (2x1)","acceso":"activo","banco":"Otro","bancoDetalle":"","numeroTarjeta":"","numeroOperacion":"ch_3TxG7lF0tn7jOn010ZR7AsTs","notas":"⚠️ Verificar acceso manualmente. Importado de export directo Stripe (Stripe Contado).","costoEmpresa":0,"costoEmpresaDivisa":"MXN","resultado":"completo"},

  // ── stripe meses 8sep.csv (Statement Descriptor: SINERGETICOS) ──
  {"evento":"LEGENDAR-IA","mes":"2026-09","plataforma":"Stripe Meses","fechaDevolucion":"2026-09-03","monto":502,"divisa":"USD","correo":"ivanrodriguez.grt@gmail.com","producto":"Legendar-IA","productoDetalle":"Certificación Legendar IA","acceso":"activo","banco":"Otro","bancoDetalle":"","numeroTarjeta":"","numeroOperacion":"ch_3UBPIeJqLlzb76TQ12DgRfFl","notas":"⚠️ Verificar acceso manualmente. Importado de export directo Stripe (Stripe Meses).","costoEmpresa":0,"costoEmpresaDivisa":"MXN","resultado":"parcial"},
  {"evento":"PRES-MX","mes":"2026-08","plataforma":"Stripe Meses","fechaDevolucion":"2026-08-28","monto":5997,"divisa":"MXN","correo":"","producto":"Club Sinergetico","productoDetalle":"Club Sinergético","acceso":"activo","banco":"Otro","bancoDetalle":"","numeroTarjeta":"","numeroOperacion":"ch_3U6kRTJqLlzb76TQ0LGMxGdV","notas":"⚠️ Verificar acceso manualmente. Importado de export directo Stripe (Stripe Meses).","costoEmpresa":0,"costoEmpresaDivisa":"MXN","resultado":"completo"},
  {"evento":"PRES-MX","mes":"2026-08","plataforma":"Stripe Meses","fechaDevolucion":"2026-08-27","monto":10397,"divisa":"MXN","correo":"lamonicadiazramos@gmail.com","producto":"Club Sinergetico","productoDetalle":"","acceso":"activo","banco":"Otro","bancoDetalle":"","numeroTarjeta":"","numeroOperacion":"py_3U5TfqJqLlzb76TQ1gcyf8P2","notas":"⚠️ Verificar acceso manualmente. Importado de export directo Stripe (Stripe Meses).","costoEmpresa":0,"costoEmpresaDivisa":"MXN","resultado":"completo"},
  {"evento":"PRES-MX","mes":"2026-08","plataforma":"Stripe Meses","fechaDevolucion":"2026-08-12","monto":5997,"divisa":"MXN","correo":"felixcarranza514@gmail.com","producto":"Club Sinergetico","productoDetalle":"","acceso":"activo","banco":"Otro","bancoDetalle":"","numeroTarjeta":"","numeroOperacion":"py_3U3hAsJqLlzb76TQ1yKIciUI","notas":"⚠️ Verificar acceso manualmente. Importado de export directo Stripe (Stripe Meses).","costoEmpresa":0,"costoEmpresaDivisa":"MXN","resultado":"completo"},
  {"evento":"PRES-MX","mes":"2026-08","plataforma":"Stripe Meses","fechaDevolucion":"2026-08-20","monto":1379,"divisa":"MXN","correo":"sacnitecristy@gmail.com","producto":"Club Sinergetico","productoDetalle":"","acceso":"activo","banco":"Otro","bancoDetalle":"","numeroTarjeta":"","numeroOperacion":"py_3U2dU9JqLlzb76TQ0HhrML13","notas":"⚠️ Verificar acceso manualmente. Importado de export directo Stripe (Stripe Meses).","costoEmpresa":0,"costoEmpresaDivisa":"MXN","resultado":"parcial"},
  {"evento":"PRES-MX","mes":"2026-09","plataforma":"Stripe Meses","fechaDevolucion":"2026-09-01","monto":11376,"divisa":"MXN","correo":"laura.franco53@gmail.com","producto":"Club Sinergetico","productoDetalle":"","acceso":"activo","banco":"Otro","bancoDetalle":"","numeroTarjeta":"","numeroOperacion":"ch_3U2d3pJqLlzb76TQ1Htr5nV9","notas":"⚠️ Verificar acceso manualmente. Importado de export directo Stripe (Stripe Meses).","costoEmpresa":0,"costoEmpresaDivisa":"MXN","resultado":"completo"},
].map(r => ({ ...r, importId: 'reembolsos-sep2026-v1' }))
